version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: ali
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
